name: AdvancementPercentage
version: Beta 4.01
author: Eli Watkins
main: dev.terrasmp.advancementpercentage.AdvancementPercentage
api-version: 1.13
#commands:
#  advtop:
#    description: yes

softdepend:
  - [PlaceholderAPI]